version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    # Mount the current directory to the workspace directory in the container
    volumes:
      - .:/workspaces
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"